/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_cost_ext_cost_0_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[8] = {12, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[11] = {1, 4, 0, 1, 2, 3, 4, 0, 0, 0, 0};
static const casadi_int casadi_s2[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s3[8] = {1, 4, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s4[8] = {1, 4, 0, 0, 1, 1, 1, 0};
static const casadi_int casadi_s5[8] = {1, 4, 0, 0, 0, 1, 1, 0};
static const casadi_int casadi_s6[8] = {1, 4, 0, 0, 0, 0, 1, 0};
static const casadi_int casadi_s7[31] = {12, 12, 0, 4, 8, 12, 16, 16, 16, 16, 16, 16, 16, 16, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s8[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s9[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s10[3] = {0, 0, 0};
static const casadi_int casadi_s11[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s12[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s13[15] = {0, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

/* Drone_ode_cost_ext_cost_0_fun_jac_hess:(i0[8],i1[4],i2[],i3[12])->(o0,o1[12],o2[12x12,16nz],o3[],o4[0x12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real w0, *w1=w+2, w2, w3, w4, w5, *w6=w+10, *w7=w+14, *w8=w+18, *w9=w+34, *w18=w+50, *w19=w+62, *w20=w+78;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x4) */
  casadi_clear(w1, 4);
  /* #2: @2 = input[1][0] */
  w2 = arg[1] ? arg[1][0] : 0;
  /* #3: @3 = input[1][1] */
  w3 = arg[1] ? arg[1][1] : 0;
  /* #4: @4 = input[1][2] */
  w4 = arg[1] ? arg[1][2] : 0;
  /* #5: @5 = input[1][3] */
  w5 = arg[1] ? arg[1][3] : 0;
  /* #6: @6 = vertcat(@2, @3, @4, @5) */
  rr=w6;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  /* #7: @7 = @6' */
  casadi_copy(w6, 4, w7);
  /* #8: @8 = zeros(4x4) */
  casadi_clear(w8, 16);
  /* #9: @2 = 0.65 */
  w2 = 6.5000000000000002e-01;
  /* #10: (@8[0] = @2) */
  for (rr=w8+0, ss=(&w2); rr!=w8+1; rr+=1) *rr = *ss++;
  /* #11: @2 = 0.65 */
  w2 = 6.5000000000000002e-01;
  /* #12: (@8[5] = @2) */
  for (rr=w8+5, ss=(&w2); rr!=w8+6; rr+=1) *rr = *ss++;
  /* #13: @2 = 0.65 */
  w2 = 6.5000000000000002e-01;
  /* #14: (@8[10] = @2) */
  for (rr=w8+10, ss=(&w2); rr!=w8+11; rr+=1) *rr = *ss++;
  /* #15: @2 = 0.65 */
  w2 = 6.5000000000000002e-01;
  /* #16: (@8[15] = @2) */
  for (rr=w8+15, ss=(&w2); rr!=w8+16; rr+=1) *rr = *ss++;
  /* #17: @1 = mac(@7,@8,@1) */
  for (i=0, rr=w1; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w7+j, tt=w8+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #18: @0 = mac(@1,@6,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w6+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #19: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #20: @1 = @1' */
  /* #21: @7 = zeros(1x4) */
  casadi_clear(w7, 4);
  /* #22: @6 = @6' */
  /* #23: @9 = @8' */
  for (i=0, rr=w9, cs=w8; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #24: @7 = mac(@6,@9,@7) */
  for (i=0, rr=w7; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w6+j, tt=w9+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #25: @7 = @7' */
  /* #26: @1 = (@1+@7) */
  for (i=0, rr=w1, cs=w7; i<4; ++i) (*rr++) += (*cs++);
  /* #27: {@0, @2, @3, @4} = vertsplit(@1) */
  w0 = w1[0];
  w2 = w1[1];
  w3 = w1[2];
  w4 = w1[3];
  /* #28: @10 = 00 */
  /* #29: @11 = 00 */
  /* #30: @12 = 00 */
  /* #31: @13 = 00 */
  /* #32: @14 = 00 */
  /* #33: @15 = 00 */
  /* #34: @16 = 00 */
  /* #35: @17 = 00 */
  /* #36: @1 = vertcat(@0, @2, @3, @4, @10, @11, @12, @13, @14, @15, @16, @17) */
  rr=w1;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  /* #37: @18 = dense(@1) */
  casadi_densify(w1, casadi_s0, w18, 0);
  /* #38: output[1][0] = @18 */
  casadi_copy(w18, 12, res[1]);
  /* #39: @19 = zeros(12x12,16nz) */
  casadi_clear(w19, 16);
  /* #40: @1 = zeros(1x4) */
  casadi_clear(w1, 4);
  /* #41: @20 = ones(12x1,9nz) */
  casadi_fill(w20, 9, 1.);
  /* #42: {@0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@20) */
  w0 = w20[0];
  /* #43: @10 = 00 */
  /* #44: @11 = 00 */
  /* #45: @12 = 00 */
  /* #46: @2 = vertcat(@0, @10, @11, @12) */
  rr=(&w2);
  *rr++ = w0;
  /* #47: @0 = @2' */
  casadi_copy((&w2), 1, (&w0));
  /* #48: @1 = mac(@0,@8,@1) */
  casadi_mtimes((&w0), casadi_s3, w8, casadi_s2, w1, casadi_s1, w, 0);
  /* #49: @1 = @1' */
  /* #50: @7 = zeros(1x4) */
  casadi_clear(w7, 4);
  /* #51: @2 = @2' */
  /* #52: @7 = mac(@2,@9,@7) */
  casadi_mtimes((&w2), casadi_s3, w9, casadi_s2, w7, casadi_s1, w, 0);
  /* #53: @7 = @7' */
  /* #54: @1 = (@1+@7) */
  for (i=0, rr=w1, cs=w7; i<4; ++i) (*rr++) += (*cs++);
  /* #55: {@2, @0, @3, @4} = vertsplit(@1) */
  w2 = w1[0];
  w0 = w1[1];
  w3 = w1[2];
  w4 = w1[3];
  /* #56: @10 = 00 */
  /* #57: @11 = 00 */
  /* #58: @12 = 00 */
  /* #59: @13 = 00 */
  /* #60: @14 = 00 */
  /* #61: @15 = 00 */
  /* #62: @16 = 00 */
  /* #63: @17 = 00 */
  /* #64: @1 = vertcat(@2, @0, @3, @4, @10, @11, @12, @13, @14, @15, @16, @17) */
  rr=w1;
  *rr++ = w2;
  *rr++ = w0;
  *rr++ = w3;
  *rr++ = w4;
  /* #65: @7 = @1[:4] */
  for (rr=w7, ss=w1+0; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #66: (@19[:4] = @7) */
  for (rr=w19+0, ss=w7; rr!=w19+4; rr+=1) *rr = *ss++;
  /* #67: @7 = @1[:4] */
  for (rr=w7, ss=w1+0; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #68: (@19[:16:4] = @7) */
  for (rr=w19+0, ss=w7; rr!=w19+16; rr+=4) *rr = *ss++;
  /* #69: @7 = zeros(1x4) */
  casadi_clear(w7, 4);
  /* #70: @10 = 00 */
  /* #71: @2 = ones(12x1,1nz) */
  w2 = 1.;
  /* #72: {NULL, @0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@2) */
  w0 = w2;
  /* #73: @11 = 00 */
  /* #74: @12 = 00 */
  /* #75: @2 = vertcat(@10, @0, @11, @12) */
  rr=(&w2);
  *rr++ = w0;
  /* #76: @0 = @2' */
  casadi_copy((&w2), 1, (&w0));
  /* #77: @7 = mac(@0,@8,@7) */
  casadi_mtimes((&w0), casadi_s4, w8, casadi_s2, w7, casadi_s1, w, 0);
  /* #78: @7 = @7' */
  /* #79: @1 = zeros(1x4) */
  casadi_clear(w1, 4);
  /* #80: @2 = @2' */
  /* #81: @1 = mac(@2,@9,@1) */
  casadi_mtimes((&w2), casadi_s4, w9, casadi_s2, w1, casadi_s1, w, 0);
  /* #82: @1 = @1' */
  /* #83: @7 = (@7+@1) */
  for (i=0, rr=w7, cs=w1; i<4; ++i) (*rr++) += (*cs++);
  /* #84: {@2, @0, @3, @4} = vertsplit(@7) */
  w2 = w7[0];
  w0 = w7[1];
  w3 = w7[2];
  w4 = w7[3];
  /* #85: @10 = 00 */
  /* #86: @11 = 00 */
  /* #87: @12 = 00 */
  /* #88: @13 = 00 */
  /* #89: @14 = 00 */
  /* #90: @15 = 00 */
  /* #91: @16 = 00 */
  /* #92: @17 = 00 */
  /* #93: @7 = vertcat(@2, @0, @3, @4, @10, @11, @12, @13, @14, @15, @16, @17) */
  rr=w7;
  *rr++ = w2;
  *rr++ = w0;
  *rr++ = w3;
  *rr++ = w4;
  /* #94: @1 = @7[:4] */
  for (rr=w1, ss=w7+0; ss!=w7+4; ss+=1) *rr++ = *ss;
  /* #95: (@19[4:8] = @1) */
  for (rr=w19+4, ss=w1; rr!=w19+8; rr+=1) *rr = *ss++;
  /* #96: @1 = @7[:4] */
  for (rr=w1, ss=w7+0; ss!=w7+4; ss+=1) *rr++ = *ss;
  /* #97: (@19[1:17:4] = @1) */
  for (rr=w19+1, ss=w1; rr!=w19+17; rr+=4) *rr = *ss++;
  /* #98: @1 = zeros(1x4) */
  casadi_clear(w1, 4);
  /* #99: @10 = 00 */
  /* #100: @11 = 00 */
  /* #101: @2 = ones(12x1,1nz) */
  w2 = 1.;
  /* #102: {NULL, NULL, @0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@2) */
  w0 = w2;
  /* #103: @12 = 00 */
  /* #104: @2 = vertcat(@10, @11, @0, @12) */
  rr=(&w2);
  *rr++ = w0;
  /* #105: @0 = @2' */
  casadi_copy((&w2), 1, (&w0));
  /* #106: @1 = mac(@0,@8,@1) */
  casadi_mtimes((&w0), casadi_s5, w8, casadi_s2, w1, casadi_s1, w, 0);
  /* #107: @1 = @1' */
  /* #108: @7 = zeros(1x4) */
  casadi_clear(w7, 4);
  /* #109: @2 = @2' */
  /* #110: @7 = mac(@2,@9,@7) */
  casadi_mtimes((&w2), casadi_s5, w9, casadi_s2, w7, casadi_s1, w, 0);
  /* #111: @7 = @7' */
  /* #112: @1 = (@1+@7) */
  for (i=0, rr=w1, cs=w7; i<4; ++i) (*rr++) += (*cs++);
  /* #113: {@2, @0, @3, @4} = vertsplit(@1) */
  w2 = w1[0];
  w0 = w1[1];
  w3 = w1[2];
  w4 = w1[3];
  /* #114: @10 = 00 */
  /* #115: @11 = 00 */
  /* #116: @12 = 00 */
  /* #117: @13 = 00 */
  /* #118: @14 = 00 */
  /* #119: @15 = 00 */
  /* #120: @16 = 00 */
  /* #121: @17 = 00 */
  /* #122: @1 = vertcat(@2, @0, @3, @4, @10, @11, @12, @13, @14, @15, @16, @17) */
  rr=w1;
  *rr++ = w2;
  *rr++ = w0;
  *rr++ = w3;
  *rr++ = w4;
  /* #123: @7 = @1[:4] */
  for (rr=w7, ss=w1+0; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #124: (@19[8:12] = @7) */
  for (rr=w19+8, ss=w7; rr!=w19+12; rr+=1) *rr = *ss++;
  /* #125: @7 = @1[:4] */
  for (rr=w7, ss=w1+0; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #126: (@19[2:18:4] = @7) */
  for (rr=w19+2, ss=w7; rr!=w19+18; rr+=4) *rr = *ss++;
  /* #127: @7 = zeros(1x4) */
  casadi_clear(w7, 4);
  /* #128: @10 = 00 */
  /* #129: @11 = 00 */
  /* #130: @12 = 00 */
  /* #131: @2 = ones(12x1,1nz) */
  w2 = 1.;
  /* #132: {NULL, NULL, NULL, @0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@2) */
  w0 = w2;
  /* #133: @2 = vertcat(@10, @11, @12, @0) */
  rr=(&w2);
  *rr++ = w0;
  /* #134: @0 = @2' */
  casadi_copy((&w2), 1, (&w0));
  /* #135: @7 = mac(@0,@8,@7) */
  casadi_mtimes((&w0), casadi_s6, w8, casadi_s2, w7, casadi_s1, w, 0);
  /* #136: @7 = @7' */
  /* #137: @1 = zeros(1x4) */
  casadi_clear(w1, 4);
  /* #138: @2 = @2' */
  /* #139: @1 = mac(@2,@9,@1) */
  casadi_mtimes((&w2), casadi_s6, w9, casadi_s2, w1, casadi_s1, w, 0);
  /* #140: @1 = @1' */
  /* #141: @7 = (@7+@1) */
  for (i=0, rr=w7, cs=w1; i<4; ++i) (*rr++) += (*cs++);
  /* #142: {@2, @0, @3, @4} = vertsplit(@7) */
  w2 = w7[0];
  w0 = w7[1];
  w3 = w7[2];
  w4 = w7[3];
  /* #143: @10 = 00 */
  /* #144: @11 = 00 */
  /* #145: @12 = 00 */
  /* #146: @13 = 00 */
  /* #147: @14 = 00 */
  /* #148: @15 = 00 */
  /* #149: @16 = 00 */
  /* #150: @17 = 00 */
  /* #151: @7 = vertcat(@2, @0, @3, @4, @10, @11, @12, @13, @14, @15, @16, @17) */
  rr=w7;
  *rr++ = w2;
  *rr++ = w0;
  *rr++ = w3;
  *rr++ = w4;
  /* #152: @1 = @7[:4] */
  for (rr=w1, ss=w7+0; ss!=w7+4; ss+=1) *rr++ = *ss;
  /* #153: (@19[12:16] = @1) */
  for (rr=w19+12, ss=w1; rr!=w19+16; rr+=1) *rr = *ss++;
  /* #154: @1 = @7[:4] */
  for (rr=w1, ss=w7+0; ss!=w7+4; ss+=1) *rr++ = *ss;
  /* #155: (@19[3:19:4] = @1) */
  for (rr=w19+3, ss=w1; rr!=w19+19; rr+=4) *rr = *ss++;
  /* #156: @9 = @19' */
  casadi_trans(w19,casadi_s7, w9, casadi_s7, iw);
  /* #157: output[2][0] = @9 */
  casadi_copy(w9, 16, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_0_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_0_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_0_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_0_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_0_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_0_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_cost_ext_cost_0_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_0_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_0_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_0_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    case 1: return casadi_s9;
    case 2: return casadi_s10;
    case 3: return casadi_s11;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_0_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s12;
    case 1: return casadi_s11;
    case 2: return casadi_s7;
    case 3: return casadi_s10;
    case 4: return casadi_s13;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 16;
  if (sz_res) *sz_res = 17;
  if (sz_iw) *sz_iw = 13;
  if (sz_w) *sz_w = 87;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
