/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

static const casadi_int casadi_s0[19] = {1, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s1[75] = {8, 8, 0, 8, 16, 24, 32, 40, 48, 56, 64, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s2[12] = {1, 8, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0};
static const casadi_int casadi_s3[12] = {1, 8, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0};
static const casadi_int casadi_s4[12] = {1, 8, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0};
static const casadi_int casadi_s5[12] = {1, 8, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0};
static const casadi_int casadi_s6[12] = {1, 8, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s7[12] = {1, 8, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0};
static const casadi_int casadi_s8[12] = {1, 8, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0};
static const casadi_int casadi_s9[12] = {1, 8, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0};
static const casadi_int casadi_s10[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s11[3] = {0, 0, 0};
static const casadi_int casadi_s12[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s13[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s14[11] = {0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0};

/* Drone_ode_cost_ext_cost_e_fun_jac_hess:(i0[8],i1[],i2[],i3[12])->(o0,o1[8],o2[8x8],o3[],o4[0x8]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real w0, *w1=w+2, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, *w14=w+22, *w15=w+34, *w16=w+42, *w17=w+50, *w18=w+114, *w19=w+178;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x8) */
  casadi_clear(w1, 8);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w3 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w4 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w5 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w6 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w7 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w8 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w9 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13) */
  rr=w14;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  /* #15: @15 = @14[:8] */
  for (rr=w15, ss=w14+0; ss!=w14+8; ss+=1) *rr++ = *ss;
  /* #16: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #17: @3 = input[0][1] */
  w3 = arg[0] ? arg[0][1] : 0;
  /* #18: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #19: @5 = input[0][3] */
  w5 = arg[0] ? arg[0][3] : 0;
  /* #20: @6 = input[0][4] */
  w6 = arg[0] ? arg[0][4] : 0;
  /* #21: @7 = input[0][5] */
  w7 = arg[0] ? arg[0][5] : 0;
  /* #22: @8 = input[0][6] */
  w8 = arg[0] ? arg[0][6] : 0;
  /* #23: @9 = input[0][7] */
  w9 = arg[0] ? arg[0][7] : 0;
  /* #24: @16 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9) */
  rr=w16;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  /* #25: @15 = (@15-@16) */
  for (i=0, rr=w15, cs=w16; i<8; ++i) (*rr++) -= (*cs++);
  /* #26: @16 = @15' */
  casadi_copy(w15, 8, w16);
  /* #27: @17 = zeros(8x8) */
  casadi_clear(w17, 64);
  /* #28: @2 = 2 */
  w2 = 2.;
  /* #29: (@17[0] = @2) */
  for (rr=w17+0, ss=(&w2); rr!=w17+1; rr+=1) *rr = *ss++;
  /* #30: @2 = 2 */
  w2 = 2.;
  /* #31: (@17[9] = @2) */
  for (rr=w17+9, ss=(&w2); rr!=w17+10; rr+=1) *rr = *ss++;
  /* #32: @2 = 2 */
  w2 = 2.;
  /* #33: (@17[18] = @2) */
  for (rr=w17+18, ss=(&w2); rr!=w17+19; rr+=1) *rr = *ss++;
  /* #34: @2 = 2 */
  w2 = 2.;
  /* #35: (@17[27] = @2) */
  for (rr=w17+27, ss=(&w2); rr!=w17+28; rr+=1) *rr = *ss++;
  /* #36: @1 = mac(@16,@17,@1) */
  for (i=0, rr=w1; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w16+j, tt=w17+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #37: @0 = mac(@1,@15,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w15+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #38: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #39: @1 = @1' */
  /* #40: @16 = zeros(1x8) */
  casadi_clear(w16, 8);
  /* #41: @15 = @15' */
  /* #42: @18 = @17' */
  for (i=0, rr=w18, cs=w17; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #43: @16 = mac(@15,@18,@16) */
  for (i=0, rr=w16; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w15+j, tt=w18+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #44: @16 = @16' */
  /* #45: @1 = (@1+@16) */
  for (i=0, rr=w1, cs=w16; i<8; ++i) (*rr++) += (*cs++);
  /* #46: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<8; ++i) *rr++ = (- *cs++ );
  /* #47: output[1][0] = @1 */
  casadi_copy(w1, 8, res[1]);
  /* #48: @19 = zeros(8x8) */
  casadi_clear(w19, 64);
  /* #49: @1 = zeros(1x8) */
  casadi_clear(w1, 8);
  /* #50: @0 = ones(8x1,1nz) */
  w0 = 1.;
  /* #51: {@2, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@0) */
  w2 = w0;
  /* #52: @20 = 00 */
  /* #53: @21 = 00 */
  /* #54: @22 = 00 */
  /* #55: @23 = 00 */
  /* #56: @24 = 00 */
  /* #57: @25 = 00 */
  /* #58: @26 = 00 */
  /* #59: @0 = vertcat(@2, @20, @21, @22, @23, @24, @25, @26) */
  rr=(&w0);
  *rr++ = w2;
  /* #60: @0 = (-@0) */
  w0 = (- w0 );
  /* #61: @2 = @0' */
  casadi_copy((&w0), 1, (&w2));
  /* #62: @1 = mac(@2,@17,@1) */
  casadi_mtimes((&w2), casadi_s2, w17, casadi_s1, w1, casadi_s0, w, 0);
  /* #63: @1 = @1' */
  /* #64: @16 = zeros(1x8) */
  casadi_clear(w16, 8);
  /* #65: @0 = @0' */
  /* #66: @16 = mac(@0,@18,@16) */
  casadi_mtimes((&w0), casadi_s2, w18, casadi_s1, w16, casadi_s0, w, 0);
  /* #67: @16 = @16' */
  /* #68: @1 = (@1+@16) */
  for (i=0, rr=w1, cs=w16; i<8; ++i) (*rr++) += (*cs++);
  /* #69: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<8; ++i) *rr++ = (- *cs++ );
  /* #70: (@19[:8] = @1) */
  for (rr=w19+0, ss=w1; rr!=w19+8; rr+=1) *rr = *ss++;
  /* #71: (@19[:64:8] = @1) */
  for (rr=w19+0, ss=w1; rr!=w19+64; rr+=8) *rr = *ss++;
  /* #72: @1 = zeros(1x8) */
  casadi_clear(w1, 8);
  /* #73: @20 = 00 */
  /* #74: @0 = ones(8x1,1nz) */
  w0 = 1.;
  /* #75: {NULL, @2, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@0) */
  w2 = w0;
  /* #76: @21 = 00 */
  /* #77: @22 = 00 */
  /* #78: @23 = 00 */
  /* #79: @24 = 00 */
  /* #80: @25 = 00 */
  /* #81: @26 = 00 */
  /* #82: @0 = vertcat(@20, @2, @21, @22, @23, @24, @25, @26) */
  rr=(&w0);
  *rr++ = w2;
  /* #83: @0 = (-@0) */
  w0 = (- w0 );
  /* #84: @2 = @0' */
  casadi_copy((&w0), 1, (&w2));
  /* #85: @1 = mac(@2,@17,@1) */
  casadi_mtimes((&w2), casadi_s3, w17, casadi_s1, w1, casadi_s0, w, 0);
  /* #86: @1 = @1' */
  /* #87: @16 = zeros(1x8) */
  casadi_clear(w16, 8);
  /* #88: @0 = @0' */
  /* #89: @16 = mac(@0,@18,@16) */
  casadi_mtimes((&w0), casadi_s3, w18, casadi_s1, w16, casadi_s0, w, 0);
  /* #90: @16 = @16' */
  /* #91: @1 = (@1+@16) */
  for (i=0, rr=w1, cs=w16; i<8; ++i) (*rr++) += (*cs++);
  /* #92: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<8; ++i) *rr++ = (- *cs++ );
  /* #93: (@19[8:16] = @1) */
  for (rr=w19+8, ss=w1; rr!=w19+16; rr+=1) *rr = *ss++;
  /* #94: (@19[1:65:8] = @1) */
  for (rr=w19+1, ss=w1; rr!=w19+65; rr+=8) *rr = *ss++;
  /* #95: @1 = zeros(1x8) */
  casadi_clear(w1, 8);
  /* #96: @20 = 00 */
  /* #97: @21 = 00 */
  /* #98: @0 = ones(8x1,1nz) */
  w0 = 1.;
  /* #99: {NULL, NULL, @2, NULL, NULL, NULL, NULL, NULL} = vertsplit(@0) */
  w2 = w0;
  /* #100: @22 = 00 */
  /* #101: @23 = 00 */
  /* #102: @24 = 00 */
  /* #103: @25 = 00 */
  /* #104: @26 = 00 */
  /* #105: @0 = vertcat(@20, @21, @2, @22, @23, @24, @25, @26) */
  rr=(&w0);
  *rr++ = w2;
  /* #106: @0 = (-@0) */
  w0 = (- w0 );
  /* #107: @2 = @0' */
  casadi_copy((&w0), 1, (&w2));
  /* #108: @1 = mac(@2,@17,@1) */
  casadi_mtimes((&w2), casadi_s4, w17, casadi_s1, w1, casadi_s0, w, 0);
  /* #109: @1 = @1' */
  /* #110: @16 = zeros(1x8) */
  casadi_clear(w16, 8);
  /* #111: @0 = @0' */
  /* #112: @16 = mac(@0,@18,@16) */
  casadi_mtimes((&w0), casadi_s4, w18, casadi_s1, w16, casadi_s0, w, 0);
  /* #113: @16 = @16' */
  /* #114: @1 = (@1+@16) */
  for (i=0, rr=w1, cs=w16; i<8; ++i) (*rr++) += (*cs++);
  /* #115: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<8; ++i) *rr++ = (- *cs++ );
  /* #116: (@19[16:24] = @1) */
  for (rr=w19+16, ss=w1; rr!=w19+24; rr+=1) *rr = *ss++;
  /* #117: (@19[2:66:8] = @1) */
  for (rr=w19+2, ss=w1; rr!=w19+66; rr+=8) *rr = *ss++;
  /* #118: @1 = zeros(1x8) */
  casadi_clear(w1, 8);
  /* #119: @20 = 00 */
  /* #120: @21 = 00 */
  /* #121: @22 = 00 */
  /* #122: @0 = ones(8x1,1nz) */
  w0 = 1.;
  /* #123: {NULL, NULL, NULL, @2, NULL, NULL, NULL, NULL} = vertsplit(@0) */
  w2 = w0;
  /* #124: @23 = 00 */
  /* #125: @24 = 00 */
  /* #126: @25 = 00 */
  /* #127: @26 = 00 */
  /* #128: @0 = vertcat(@20, @21, @22, @2, @23, @24, @25, @26) */
  rr=(&w0);
  *rr++ = w2;
  /* #129: @0 = (-@0) */
  w0 = (- w0 );
  /* #130: @2 = @0' */
  casadi_copy((&w0), 1, (&w2));
  /* #131: @1 = mac(@2,@17,@1) */
  casadi_mtimes((&w2), casadi_s5, w17, casadi_s1, w1, casadi_s0, w, 0);
  /* #132: @1 = @1' */
  /* #133: @16 = zeros(1x8) */
  casadi_clear(w16, 8);
  /* #134: @0 = @0' */
  /* #135: @16 = mac(@0,@18,@16) */
  casadi_mtimes((&w0), casadi_s5, w18, casadi_s1, w16, casadi_s0, w, 0);
  /* #136: @16 = @16' */
  /* #137: @1 = (@1+@16) */
  for (i=0, rr=w1, cs=w16; i<8; ++i) (*rr++) += (*cs++);
  /* #138: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<8; ++i) *rr++ = (- *cs++ );
  /* #139: (@19[24:32] = @1) */
  for (rr=w19+24, ss=w1; rr!=w19+32; rr+=1) *rr = *ss++;
  /* #140: (@19[3:67:8] = @1) */
  for (rr=w19+3, ss=w1; rr!=w19+67; rr+=8) *rr = *ss++;
  /* #141: @1 = zeros(1x8) */
  casadi_clear(w1, 8);
  /* #142: @20 = 00 */
  /* #143: @21 = 00 */
  /* #144: @22 = 00 */
  /* #145: @23 = 00 */
  /* #146: @0 = ones(8x1,1nz) */
  w0 = 1.;
  /* #147: {NULL, NULL, NULL, NULL, @2, NULL, NULL, NULL} = vertsplit(@0) */
  w2 = w0;
  /* #148: @24 = 00 */
  /* #149: @25 = 00 */
  /* #150: @26 = 00 */
  /* #151: @0 = vertcat(@20, @21, @22, @23, @2, @24, @25, @26) */
  rr=(&w0);
  *rr++ = w2;
  /* #152: @0 = (-@0) */
  w0 = (- w0 );
  /* #153: @2 = @0' */
  casadi_copy((&w0), 1, (&w2));
  /* #154: @1 = mac(@2,@17,@1) */
  casadi_mtimes((&w2), casadi_s6, w17, casadi_s1, w1, casadi_s0, w, 0);
  /* #155: @1 = @1' */
  /* #156: @16 = zeros(1x8) */
  casadi_clear(w16, 8);
  /* #157: @0 = @0' */
  /* #158: @16 = mac(@0,@18,@16) */
  casadi_mtimes((&w0), casadi_s6, w18, casadi_s1, w16, casadi_s0, w, 0);
  /* #159: @16 = @16' */
  /* #160: @1 = (@1+@16) */
  for (i=0, rr=w1, cs=w16; i<8; ++i) (*rr++) += (*cs++);
  /* #161: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<8; ++i) *rr++ = (- *cs++ );
  /* #162: (@19[32:40] = @1) */
  for (rr=w19+32, ss=w1; rr!=w19+40; rr+=1) *rr = *ss++;
  /* #163: (@19[4:68:8] = @1) */
  for (rr=w19+4, ss=w1; rr!=w19+68; rr+=8) *rr = *ss++;
  /* #164: @1 = zeros(1x8) */
  casadi_clear(w1, 8);
  /* #165: @20 = 00 */
  /* #166: @21 = 00 */
  /* #167: @22 = 00 */
  /* #168: @23 = 00 */
  /* #169: @24 = 00 */
  /* #170: @0 = ones(8x1,1nz) */
  w0 = 1.;
  /* #171: {NULL, NULL, NULL, NULL, NULL, @2, NULL, NULL} = vertsplit(@0) */
  w2 = w0;
  /* #172: @25 = 00 */
  /* #173: @26 = 00 */
  /* #174: @0 = vertcat(@20, @21, @22, @23, @24, @2, @25, @26) */
  rr=(&w0);
  *rr++ = w2;
  /* #175: @0 = (-@0) */
  w0 = (- w0 );
  /* #176: @2 = @0' */
  casadi_copy((&w0), 1, (&w2));
  /* #177: @1 = mac(@2,@17,@1) */
  casadi_mtimes((&w2), casadi_s7, w17, casadi_s1, w1, casadi_s0, w, 0);
  /* #178: @1 = @1' */
  /* #179: @16 = zeros(1x8) */
  casadi_clear(w16, 8);
  /* #180: @0 = @0' */
  /* #181: @16 = mac(@0,@18,@16) */
  casadi_mtimes((&w0), casadi_s7, w18, casadi_s1, w16, casadi_s0, w, 0);
  /* #182: @16 = @16' */
  /* #183: @1 = (@1+@16) */
  for (i=0, rr=w1, cs=w16; i<8; ++i) (*rr++) += (*cs++);
  /* #184: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<8; ++i) *rr++ = (- *cs++ );
  /* #185: (@19[40:48] = @1) */
  for (rr=w19+40, ss=w1; rr!=w19+48; rr+=1) *rr = *ss++;
  /* #186: (@19[5:69:8] = @1) */
  for (rr=w19+5, ss=w1; rr!=w19+69; rr+=8) *rr = *ss++;
  /* #187: @1 = zeros(1x8) */
  casadi_clear(w1, 8);
  /* #188: @20 = 00 */
  /* #189: @21 = 00 */
  /* #190: @22 = 00 */
  /* #191: @23 = 00 */
  /* #192: @24 = 00 */
  /* #193: @25 = 00 */
  /* #194: @0 = ones(8x1,1nz) */
  w0 = 1.;
  /* #195: {NULL, NULL, NULL, NULL, NULL, NULL, @2, NULL} = vertsplit(@0) */
  w2 = w0;
  /* #196: @26 = 00 */
  /* #197: @0 = vertcat(@20, @21, @22, @23, @24, @25, @2, @26) */
  rr=(&w0);
  *rr++ = w2;
  /* #198: @0 = (-@0) */
  w0 = (- w0 );
  /* #199: @2 = @0' */
  casadi_copy((&w0), 1, (&w2));
  /* #200: @1 = mac(@2,@17,@1) */
  casadi_mtimes((&w2), casadi_s8, w17, casadi_s1, w1, casadi_s0, w, 0);
  /* #201: @1 = @1' */
  /* #202: @16 = zeros(1x8) */
  casadi_clear(w16, 8);
  /* #203: @0 = @0' */
  /* #204: @16 = mac(@0,@18,@16) */
  casadi_mtimes((&w0), casadi_s8, w18, casadi_s1, w16, casadi_s0, w, 0);
  /* #205: @16 = @16' */
  /* #206: @1 = (@1+@16) */
  for (i=0, rr=w1, cs=w16; i<8; ++i) (*rr++) += (*cs++);
  /* #207: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<8; ++i) *rr++ = (- *cs++ );
  /* #208: (@19[48:56] = @1) */
  for (rr=w19+48, ss=w1; rr!=w19+56; rr+=1) *rr = *ss++;
  /* #209: (@19[6:70:8] = @1) */
  for (rr=w19+6, ss=w1; rr!=w19+70; rr+=8) *rr = *ss++;
  /* #210: @1 = zeros(1x8) */
  casadi_clear(w1, 8);
  /* #211: @20 = 00 */
  /* #212: @21 = 00 */
  /* #213: @22 = 00 */
  /* #214: @23 = 00 */
  /* #215: @24 = 00 */
  /* #216: @25 = 00 */
  /* #217: @26 = 00 */
  /* #218: @0 = ones(8x1,1nz) */
  w0 = 1.;
  /* #219: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, @2} = vertsplit(@0) */
  w2 = w0;
  /* #220: @0 = vertcat(@20, @21, @22, @23, @24, @25, @26, @2) */
  rr=(&w0);
  *rr++ = w2;
  /* #221: @0 = (-@0) */
  w0 = (- w0 );
  /* #222: @2 = @0' */
  casadi_copy((&w0), 1, (&w2));
  /* #223: @1 = mac(@2,@17,@1) */
  casadi_mtimes((&w2), casadi_s9, w17, casadi_s1, w1, casadi_s0, w, 0);
  /* #224: @1 = @1' */
  /* #225: @16 = zeros(1x8) */
  casadi_clear(w16, 8);
  /* #226: @0 = @0' */
  /* #227: @16 = mac(@0,@18,@16) */
  casadi_mtimes((&w0), casadi_s9, w18, casadi_s1, w16, casadi_s0, w, 0);
  /* #228: @16 = @16' */
  /* #229: @1 = (@1+@16) */
  for (i=0, rr=w1, cs=w16; i<8; ++i) (*rr++) += (*cs++);
  /* #230: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<8; ++i) *rr++ = (- *cs++ );
  /* #231: (@19[56:64] = @1) */
  for (rr=w19+56, ss=w1; rr!=w19+64; rr+=1) *rr = *ss++;
  /* #232: (@19[7:71:8] = @1) */
  for (rr=w19+7, ss=w1; rr!=w19+71; rr+=8) *rr = *ss++;
  /* #233: @18 = @19' */
  for (i=0, rr=w18, cs=w19; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #234: output[2][0] = @18 */
  casadi_copy(w18, 64, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s10;
    case 1: return casadi_s11;
    case 2: return casadi_s11;
    case 3: return casadi_s12;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s13;
    case 1: return casadi_s10;
    case 2: return casadi_s1;
    case 3: return casadi_s11;
    case 4: return casadi_s14;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 16;
  if (sz_res) *sz_res = 13;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 242;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
