/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

static const casadi_int casadi_s0[4] = {0, 1, 2, 3};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[17] = {4, 4, 0, 4, 7, 9, 10, 0, 1, 2, 3, 1, 2, 3, 2, 3, 3};
static const casadi_int casadi_s3[17] = {4, 4, 0, 1, 3, 6, 10, 0, 0, 1, 0, 1, 2, 0, 1, 2, 3};
static const casadi_int casadi_s4[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s5[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s6[13] = {1, 8, 0, 1, 2, 2, 2, 2, 2, 2, 2, 0, 0};
static const casadi_int casadi_s7[11] = {1, 4, 0, 1, 2, 3, 4, 0, 0, 0, 0};
static const casadi_int casadi_s8[39] = {8, 4, 0, 8, 16, 24, 32, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s9[43] = {4, 8, 0, 4, 8, 12, 16, 20, 24, 28, 32, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s10[6] = {8, 1, 0, 2, 0, 1};
static const casadi_int casadi_s11[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s12[3] = {0, 0, 0};
static const casadi_int casadi_s13[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s14[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s15[29] = {12, 2, 0, 12, 24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s16[3] = {2, 0, 0};

static const casadi_real casadi_c0[16] = {1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.};

/* Drone_ode_constr_h_fun_jac_uxt_zt:(i0[8],i1[4],i2[],i3[12])->(o0[2],o1[12x2],o2[2x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cr, *cs;
  casadi_real w0, *w1=w+9, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, *w14=w+29, *w15=w+41, *w16=w+49, *w17=w+57, *w18=w+65, *w19=w+129, *w20=w+145, *w21=w+161, *w22=w+193, *w23=w+225, *w24=w+241, *w25=w+257, *w26=w+273, *w27=w+305, *w28=w+369, *w29=w+433, *w30=w+441, *w31=w+445, *w32=w+453, *w33=w+461, *w34=w+463, w35, w36, *w37=w+472, *w38=w+474, *w39=w+478, *w40=w+502, w41, w42, w43, *w44=w+509, w45, *w46=w+518, w47, w48;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x8) */
  casadi_clear(w1, 8);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w3 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w4 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w5 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w6 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w7 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w8 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w9 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13) */
  rr=w14;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  /* #15: @15 = @14[:8] */
  for (rr=w15, ss=w14+0; ss!=w14+8; ss+=1) *rr++ = *ss;
  /* #16: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #17: @3 = input[0][1] */
  w3 = arg[0] ? arg[0][1] : 0;
  /* #18: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #19: @5 = input[0][3] */
  w5 = arg[0] ? arg[0][3] : 0;
  /* #20: @6 = input[0][4] */
  w6 = arg[0] ? arg[0][4] : 0;
  /* #21: @7 = input[0][5] */
  w7 = arg[0] ? arg[0][5] : 0;
  /* #22: @8 = input[0][6] */
  w8 = arg[0] ? arg[0][6] : 0;
  /* #23: @9 = input[0][7] */
  w9 = arg[0] ? arg[0][7] : 0;
  /* #24: @16 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9) */
  rr=w16;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  /* #25: @15 = (@15-@16) */
  for (i=0, rr=w15, cs=w16; i<8; ++i) (*rr++) -= (*cs++);
  /* #26: @17 = @15' */
  casadi_copy(w15, 8, w17);
  /* #27: @17 = (-@17) */
  for (i=0, rr=w17, cs=w17; i<8; ++i) *rr++ = (- *cs++ );
  /* #28: @18 = zeros(8x8) */
  casadi_clear(w18, 64);
  /* #29: @4 = 2 */
  w4 = 2.;
  /* #30: (@18[0] = @4) */
  for (rr=w18+0, ss=(&w4); rr!=w18+1; rr+=1) *rr = *ss++;
  /* #31: @4 = 2 */
  w4 = 2.;
  /* #32: (@18[9] = @4) */
  for (rr=w18+9, ss=(&w4); rr!=w18+10; rr+=1) *rr = *ss++;
  /* #33: @4 = 2 */
  w4 = 2.;
  /* #34: (@18[18] = @4) */
  for (rr=w18+18, ss=(&w4); rr!=w18+19; rr+=1) *rr = *ss++;
  /* #35: @4 = 2 */
  w4 = 2.;
  /* #36: (@18[27] = @4) */
  for (rr=w18+27, ss=(&w4); rr!=w18+28; rr+=1) *rr = *ss++;
  /* #37: @1 = mac(@17,@18,@1) */
  for (i=0, rr=w1; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w17+j, tt=w18+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #38: @17 = zeros(8x1) */
  casadi_clear(w17, 8);
  /* #39: @19 = zeros(4x4) */
  casadi_clear(w19, 16);
  /* #40: @20 = zeros(4x4) */
  casadi_clear(w20, 16);
  /* #41: @4 = cos(@5) */
  w4 = cos( w5 );
  /* #42: (@20[0] = @4) */
  for (rr=w20+0, ss=(&w4); rr!=w20+1; rr+=1) *rr = *ss++;
  /* #43: @4 = sin(@5) */
  w4 = sin( w5 );
  /* #44: @4 = (-@4) */
  w4 = (- w4 );
  /* #45: (@20[4] = @4) */
  for (rr=w20+4, ss=(&w4); rr!=w20+5; rr+=1) *rr = *ss++;
  /* #46: @4 = 0 */
  w4 = 0.;
  /* #47: (@20[8] = @4) */
  for (rr=w20+8, ss=(&w4); rr!=w20+9; rr+=1) *rr = *ss++;
  /* #48: @4 = 0 */
  w4 = 0.;
  /* #49: (@20[12] = @4) */
  for (rr=w20+12, ss=(&w4); rr!=w20+13; rr+=1) *rr = *ss++;
  /* #50: @4 = sin(@5) */
  w4 = sin( w5 );
  /* #51: (@20[1] = @4) */
  for (rr=w20+1, ss=(&w4); rr!=w20+2; rr+=1) *rr = *ss++;
  /* #52: @4 = cos(@5) */
  w4 = cos( w5 );
  /* #53: (@20[5] = @4) */
  for (rr=w20+5, ss=(&w4); rr!=w20+6; rr+=1) *rr = *ss++;
  /* #54: @4 = 0 */
  w4 = 0.;
  /* #55: (@20[9] = @4) */
  for (rr=w20+9, ss=(&w4); rr!=w20+10; rr+=1) *rr = *ss++;
  /* #56: @4 = 0 */
  w4 = 0.;
  /* #57: (@20[13] = @4) */
  for (rr=w20+13, ss=(&w4); rr!=w20+14; rr+=1) *rr = *ss++;
  /* #58: @4 = 0 */
  w4 = 0.;
  /* #59: (@20[2] = @4) */
  for (rr=w20+2, ss=(&w4); rr!=w20+3; rr+=1) *rr = *ss++;
  /* #60: @4 = 0 */
  w4 = 0.;
  /* #61: (@20[6] = @4) */
  for (rr=w20+6, ss=(&w4); rr!=w20+7; rr+=1) *rr = *ss++;
  /* #62: @4 = 1 */
  w4 = 1.;
  /* #63: (@20[10] = @4) */
  for (rr=w20+10, ss=(&w4); rr!=w20+11; rr+=1) *rr = *ss++;
  /* #64: @4 = 0 */
  w4 = 0.;
  /* #65: (@20[14] = @4) */
  for (rr=w20+14, ss=(&w4); rr!=w20+15; rr+=1) *rr = *ss++;
  /* #66: @4 = 0 */
  w4 = 0.;
  /* #67: (@20[3] = @4) */
  for (rr=w20+3, ss=(&w4); rr!=w20+4; rr+=1) *rr = *ss++;
  /* #68: @4 = 0 */
  w4 = 0.;
  /* #69: (@20[7] = @4) */
  for (rr=w20+7, ss=(&w4); rr!=w20+8; rr+=1) *rr = *ss++;
  /* #70: @4 = 0 */
  w4 = 0.;
  /* #71: (@20[11] = @4) */
  for (rr=w20+11, ss=(&w4); rr!=w20+12; rr+=1) *rr = *ss++;
  /* #72: @4 = 1 */
  w4 = 1.;
  /* #73: (@20[15] = @4) */
  for (rr=w20+15, ss=(&w4); rr!=w20+16; rr+=1) *rr = *ss++;
  /* #74: @21 = horzcat(@19, @20) */
  rr=w21;
  for (i=0, cs=w19; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<16; ++i) *rr++ = *cs++;
  /* #75: @22 = @21' */
  for (i=0, rr=w22, cs=w21; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #76: @19 = zeros(4x4) */
  casadi_clear(w19, 16);
  /* #77: @20 = zeros(4x4) */
  casadi_clear(w20, 16);
  /* #78: @23 = 
  [[1, 0, 0, 0], 
   [0, 1, 0, 0], 
   [0, 0, 1, 0], 
   [0, 0, 0, 1]] */
  casadi_copy(casadi_c0, 16, w23);
  /* #79: @24 = zeros(4x4) */
  casadi_clear(w24, 16);
  /* #80: @4 = 0.6756 */
  w4 = 6.7559999999999998e-01;
  /* #81: (@24[0] = @4) */
  for (rr=w24+0, ss=(&w4); rr!=w24+1; rr+=1) *rr = *ss++;
  /* #82: @4 = 0 */
  w4 = 0.;
  /* #83: (@24[4] = @4) */
  for (rr=w24+4, ss=(&w4); rr!=w24+5; rr+=1) *rr = *ss++;
  /* #84: @4 = 0 */
  w4 = 0.;
  /* #85: (@24[8] = @4) */
  for (rr=w24+8, ss=(&w4); rr!=w24+9; rr+=1) *rr = *ss++;
  /* #86: @4 = 0 */
  w4 = 0.;
  /* #87: (@24[12] = @4) */
  for (rr=w24+12, ss=(&w4); rr!=w24+13; rr+=1) *rr = *ss++;
  /* #88: @4 = 0 */
  w4 = 0.;
  /* #89: (@24[1] = @4) */
  for (rr=w24+1, ss=(&w4); rr!=w24+2; rr+=1) *rr = *ss++;
  /* #90: @4 = 0.6344 */
  w4 = 6.3439999999999996e-01;
  /* #91: (@24[5] = @4) */
  for (rr=w24+5, ss=(&w4); rr!=w24+6; rr+=1) *rr = *ss++;
  /* #92: @4 = 0 */
  w4 = 0.;
  /* #93: (@24[9] = @4) */
  for (rr=w24+9, ss=(&w4); rr!=w24+10; rr+=1) *rr = *ss++;
  /* #94: @4 = 0 */
  w4 = 0.;
  /* #95: (@24[13] = @4) */
  for (rr=w24+13, ss=(&w4); rr!=w24+14; rr+=1) *rr = *ss++;
  /* #96: @4 = 0 */
  w4 = 0.;
  /* #97: (@24[2] = @4) */
  for (rr=w24+2, ss=(&w4); rr!=w24+3; rr+=1) *rr = *ss++;
  /* #98: @4 = 0 */
  w4 = 0.;
  /* #99: (@24[6] = @4) */
  for (rr=w24+6, ss=(&w4); rr!=w24+7; rr+=1) *rr = *ss++;
  /* #100: @4 = 0.408 */
  w4 = 4.0799999999999997e-01;
  /* #101: (@24[10] = @4) */
  for (rr=w24+10, ss=(&w4); rr!=w24+11; rr+=1) *rr = *ss++;
  /* #102: @4 = 0 */
  w4 = 0.;
  /* #103: (@24[14] = @4) */
  for (rr=w24+14, ss=(&w4); rr!=w24+15; rr+=1) *rr = *ss++;
  /* #104: @4 = 0 */
  w4 = 0.;
  /* #105: (@24[3] = @4) */
  for (rr=w24+3, ss=(&w4); rr!=w24+4; rr+=1) *rr = *ss++;
  /* #106: @4 = 0 */
  w4 = 0.;
  /* #107: (@24[7] = @4) */
  for (rr=w24+7, ss=(&w4); rr!=w24+8; rr+=1) *rr = *ss++;
  /* #108: @4 = 0 */
  w4 = 0.;
  /* #109: (@24[11] = @4) */
  for (rr=w24+11, ss=(&w4); rr!=w24+12; rr+=1) *rr = *ss++;
  /* #110: @4 = 0.2953 */
  w4 = 2.9530000000000001e-01;
  /* #111: (@24[15] = @4) */
  for (rr=w24+15, ss=(&w4); rr!=w24+16; rr+=1) *rr = *ss++;
  /* #112: @23 = (@24\@23) */
  rr = w23;
  ss = w24;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[10], r[10], beta[4], w[8];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 4, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #113: @25 = zeros(4x4) */
  casadi_clear(w25, 16);
  /* #114: @4 = 0.5941 */
  w4 = 5.9409999999999996e-01;
  /* #115: (@25[0] = @4) */
  for (rr=w25+0, ss=(&w4); rr!=w25+1; rr+=1) *rr = *ss++;
  /* #116: @4 = -0.8109 */
  w4 = -8.1089999999999995e-01;
  /* #117: @6 = (@4*@9) */
  w6  = (w4*w9);
  /* #118: (@25[4] = @6) */
  for (rr=w25+4, ss=(&w6); rr!=w25+5; rr+=1) *rr = *ss++;
  /* #119: @6 = 0 */
  w6 = 0.;
  /* #120: (@25[8] = @6) */
  for (rr=w25+8, ss=(&w6); rr!=w25+9; rr+=1) *rr = *ss++;
  /* #121: @6 = 0 */
  w6 = 0.;
  /* #122: (@25[12] = @6) */
  for (rr=w25+12, ss=(&w6); rr!=w25+13; rr+=1) *rr = *ss++;
  /* #123: @6 = 0.3984 */
  w6 = 3.9839999999999998e-01;
  /* #124: @9 = (@6*@9) */
  w9  = (w6*w9);
  /* #125: (@25[1] = @9) */
  for (rr=w25+1, ss=(&w9); rr!=w25+2; rr+=1) *rr = *ss++;
  /* #126: @9 = 0.704 */
  w9 = 7.0399999999999996e-01;
  /* #127: (@25[5] = @9) */
  for (rr=w25+5, ss=(&w9); rr!=w25+6; rr+=1) *rr = *ss++;
  /* #128: @9 = 0 */
  w9 = 0.;
  /* #129: (@25[9] = @9) */
  for (rr=w25+9, ss=(&w9); rr!=w25+10; rr+=1) *rr = *ss++;
  /* #130: @9 = 0 */
  w9 = 0.;
  /* #131: (@25[13] = @9) */
  for (rr=w25+13, ss=(&w9); rr!=w25+14; rr+=1) *rr = *ss++;
  /* #132: @9 = 0 */
  w9 = 0.;
  /* #133: (@25[2] = @9) */
  for (rr=w25+2, ss=(&w9); rr!=w25+3; rr+=1) *rr = *ss++;
  /* #134: @9 = 0 */
  w9 = 0.;
  /* #135: (@25[6] = @9) */
  for (rr=w25+6, ss=(&w9); rr!=w25+7; rr+=1) *rr = *ss++;
  /* #136: @9 = 0.9365 */
  w9 = 9.3650000000000000e-01;
  /* #137: (@25[10] = @9) */
  for (rr=w25+10, ss=(&w9); rr!=w25+11; rr+=1) *rr = *ss++;
  /* #138: @9 = 0 */
  w9 = 0.;
  /* #139: (@25[14] = @9) */
  for (rr=w25+14, ss=(&w9); rr!=w25+15; rr+=1) *rr = *ss++;
  /* #140: @9 = 0 */
  w9 = 0.;
  /* #141: (@25[3] = @9) */
  for (rr=w25+3, ss=(&w9); rr!=w25+4; rr+=1) *rr = *ss++;
  /* #142: @9 = 0 */
  w9 = 0.;
  /* #143: (@25[7] = @9) */
  for (rr=w25+7, ss=(&w9); rr!=w25+8; rr+=1) *rr = *ss++;
  /* #144: @9 = 0 */
  w9 = 0.;
  /* #145: (@25[11] = @9) */
  for (rr=w25+11, ss=(&w9); rr!=w25+12; rr+=1) *rr = *ss++;
  /* #146: @9 = 0.9752 */
  w9 = 9.7519999999999996e-01;
  /* #147: (@25[15] = @9) */
  for (rr=w25+15, ss=(&w9); rr!=w25+16; rr+=1) *rr = *ss++;
  /* #148: @20 = mac(@23,@25,@20) */
  for (i=0, rr=w20; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w23+j, tt=w25+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #149: @20 = (-@20) */
  for (i=0, rr=w20, cs=w20; i<16; ++i) *rr++ = (- *cs++ );
  /* #150: @21 = horzcat(@19, @20) */
  rr=w21;
  for (i=0, cs=w19; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<16; ++i) *rr++ = *cs++;
  /* #151: @26 = @21' */
  for (i=0, rr=w26, cs=w21; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #152: @27 = horzcat(@22, @26) */
  rr=w27;
  for (i=0, cs=w22; i<32; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<32; ++i) *rr++ = *cs++;
  /* #153: @28 = @27' */
  for (i=0, rr=w28, cs=w27; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #154: @17 = mac(@28,@16,@17) */
  for (i=0, rr=w17; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w28+j, tt=w16+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #155: @29 = zeros(8x1) */
  casadi_clear(w29, 8);
  /* #156: @19 = zeros(4x4) */
  casadi_clear(w19, 16);
  /* #157: @20 = 
  [[1, 0, 0, 0], 
   [0, 1, 0, 0], 
   [0, 0, 1, 0], 
   [0, 0, 0, 1]] */
  casadi_copy(casadi_c0, 16, w20);
  /* #158: @20 = (@24\@20) */
  rr = w20;
  ss = w24;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[10], r[10], beta[4], w[8];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 4, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #159: @24 = @20' */
  for (i=0, rr=w24, cs=w20; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #160: @22 = horzcat(@19, @24) */
  rr=w22;
  for (i=0, cs=w19; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<16; ++i) *rr++ = *cs++;
  /* #161: @26 = @22' */
  for (i=0, rr=w26, cs=w22; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #162: @9 = input[1][0] */
  w9 = arg[1] ? arg[1][0] : 0;
  /* #163: @7 = input[1][1] */
  w7 = arg[1] ? arg[1][1] : 0;
  /* #164: @8 = input[1][2] */
  w8 = arg[1] ? arg[1][2] : 0;
  /* #165: @10 = input[1][3] */
  w10 = arg[1] ? arg[1][3] : 0;
  /* #166: @30 = vertcat(@9, @7, @8, @10) */
  rr=w30;
  *rr++ = w9;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w10;
  /* #167: @29 = mac(@26,@30,@29) */
  for (i=0, rr=w29; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w26+j, tt=w30+i*4; k<4; ++k) *rr += ss[k*8]**tt++;
  /* #168: @29 = (@17+@29) */
  for (i=0, rr=w29, cr=w17, cs=w29; i<8; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #169: @0 = mac(@1,@29,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w29+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #170: @9 = 0.9 */
  w9 = 9.0000000000000002e-01;
  /* #171: @7 = 0 */
  w7 = 0.;
  /* #172: @31 = zeros(1x8) */
  casadi_clear(w31, 8);
  /* #173: @8 = 0.5 */
  w8 = 5.0000000000000000e-01;
  /* #174: @32 = @15' */
  casadi_copy(w15, 8, w32);
  /* #175: @32 = (@8*@32) */
  for (i=0, rr=w32, cs=w32; i<8; ++i) (*rr++)  = (w8*(*cs++));
  /* #176: @31 = mac(@32,@18,@31) */
  for (i=0, rr=w31; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w32+j, tt=w18+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #177: @7 = mac(@31,@15,@7) */
  for (i=0, rr=(&w7); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w31+j, tt=w15+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #178: @7 = (@9*@7) */
  w7  = (w9*w7);
  /* #179: @0 = (@0+@7) */
  w0 += w7;
  /* #180: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #181: @0 = 0 */
  w0 = 0.;
  /* #182: @33 = zeros(8x1,2nz) */
  casadi_clear(w33, 2);
  /* #183: @7 = 2.9 */
  w7 = 2.8999999999999999e+00;
  /* #184: @2 = (@2-@7) */
  w2 -= w7;
  /* #185: @7 = (2.*@2) */
  w7 = (2.* w2 );
  /* #186: @34 = ones(8x1,7nz) */
  casadi_fill(w34, 7, 1.);
  /* #187: {@10, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@34) */
  w10 = w34[0];
  /* #188: @7 = (@7*@10) */
  w7 *= w10;
  /* #189: @11 = sq(@2) */
  w11 = casadi_sq( w2 );
  /* #190: @12 = 0.17 */
  w12 = 1.7000000000000001e-01;
  /* #191: @3 = (@3-@12) */
  w3 -= w12;
  /* #192: @12 = sq(@3) */
  w12 = casadi_sq( w3 );
  /* #193: @11 = (@11+@12) */
  w11 += w12;
  /* #194: @11 = sqrt(@11) */
  w11 = sqrt( w11 );
  /* #195: @12 = (2.*@11) */
  w12 = (2.* w11 );
  /* #196: @7 = (@7/@12) */
  w7 /= w12;
  /* #197: @13 = (-@7) */
  w13 = (- w7 );
  /* #198: (@33[0] = @13) */
  for (rr=w33+0, ss=(&w13); rr!=w33+1; rr+=1) *rr = *ss++;
  /* #199: @13 = (2.*@3) */
  w13 = (2.* w3 );
  /* #200: @35 = ones(8x1,1nz) */
  w35 = 1.;
  /* #201: {NULL, @36, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@35) */
  w36 = w35;
  /* #202: @13 = (@13*@36) */
  w13 *= w36;
  /* #203: @13 = (@13/@12) */
  w13 /= w12;
  /* #204: @35 = (-@13) */
  w35 = (- w13 );
  /* #205: (@33[1] = @35) */
  for (rr=w33+1, ss=(&w35); rr!=w33+2; rr+=1) *rr = *ss++;
  /* #206: @37 = @33' */
  casadi_copy(w33, 2, w37);
  /* #207: @0 = mac(@37,@17,@0) */
  casadi_mtimes(w37, casadi_s6, w17, casadi_s5, (&w0), casadi_s4, w, 0);
  /* #208: @35 = 0 */
  w35 = 0.;
  /* #209: @38 = zeros(1x4) */
  casadi_clear(w38, 4);
  /* #210: @38 = mac(@37,@26,@38) */
  casadi_mtimes(w37, casadi_s6, w26, casadi_s8, w38, casadi_s7, w, 0);
  /* #211: @35 = mac(@38,@30,@35) */
  for (i=0, rr=(&w35); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w38+j, tt=w30+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #212: @0 = (@0+@35) */
  w0 += w35;
  /* #213: @35 = 0.8 */
  w35 = 8.0000000000000004e-01;
  /* #214: @35 = (@35-@11) */
  w35 -= w11;
  /* #215: @0 = (@0+@35) */
  w0 += w35;
  /* #216: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  /* #217: @39 = zeros(12x2) */
  casadi_clear(w39, 24);
  /* #218: @40 = zeros(4x1) */
  casadi_clear(w40, 4);
  /* #219: @1 = @1' */
  /* #220: @0 = ones(2x1,1nz) */
  w0 = 1.;
  /* #221: {@35, NULL} = vertsplit(@0) */
  w35 = w0;
  /* #222: @1 = (@1*@35) */
  for (i=0, rr=w1; i<8; ++i) (*rr++) *= w35;
  /* #223: @40 = mac(@22,@1,@40) */
  for (i=0, rr=w40; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w22+j, tt=w1+i*8; k<8; ++k) *rr += ss[k*4]**tt++;
  /* #224: {@0, @41, @42, @43} = vertsplit(@40) */
  w0 = w40[0];
  w41 = w40[1];
  w42 = w40[2];
  w43 = w40[3];
  /* #225: (@39[0] = @0) */
  for (rr=w39+0, ss=(&w0); rr!=w39+1; rr+=1) *rr = *ss++;
  /* #226: (@39[1] = @41) */
  for (rr=w39+1, ss=(&w41); rr!=w39+2; rr+=1) *rr = *ss++;
  /* #227: (@39[2] = @42) */
  for (rr=w39+2, ss=(&w42); rr!=w39+3; rr+=1) *rr = *ss++;
  /* #228: (@39[3] = @43) */
  for (rr=w39+3, ss=(&w43); rr!=w39+4; rr+=1) *rr = *ss++;
  /* #229: @32 = zeros(8x1) */
  casadi_clear(w32, 8);
  /* #230: @32 = mac(@27,@1,@32) */
  for (i=0, rr=w32; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w27+j, tt=w1+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #231: @31 = @31' */
  /* #232: @9 = (@9*@35) */
  w9 *= w35;
  /* #233: @31 = (@31*@9) */
  for (i=0, rr=w31; i<8; ++i) (*rr++) *= w9;
  /* #234: @44 = zeros(1x8) */
  casadi_clear(w44, 8);
  /* #235: @15 = @15' */
  /* #236: @15 = (@9*@15) */
  for (i=0, rr=w15, cs=w15; i<8; ++i) (*rr++)  = (w9*(*cs++));
  /* #237: @28 = @18' */
  for (i=0, rr=w28, cs=w18; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #238: @44 = mac(@15,@28,@44) */
  for (i=0, rr=w44; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w15+j, tt=w28+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #239: @44 = (@8*@44) */
  for (i=0, rr=w44, cs=w44; i<8; ++i) (*rr++)  = (w8*(*cs++));
  /* #240: @44 = @44' */
  /* #241: @31 = (@31+@44) */
  for (i=0, rr=w31, cs=w44; i<8; ++i) (*rr++) += (*cs++);
  /* #242: @44 = zeros(1x8) */
  casadi_clear(w44, 8);
  /* #243: @29 = @29' */
  /* #244: @29 = (@35*@29) */
  for (i=0, rr=w29, cs=w29; i<8; ++i) (*rr++)  = (w35*(*cs++));
  /* #245: @28 = @18' */
  for (i=0, rr=w28, cs=w18; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #246: @44 = mac(@29,@28,@44) */
  for (i=0, rr=w44; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w29+j, tt=w28+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #247: @44 = (-@44) */
  for (i=0, rr=w44, cs=w44; i<8; ++i) *rr++ = (- *cs++ );
  /* #248: @44 = @44' */
  /* #249: @31 = (@31+@44) */
  for (i=0, rr=w31, cs=w44; i<8; ++i) (*rr++) += (*cs++);
  /* #250: @32 = (@32-@31) */
  for (i=0, rr=w32, cs=w31; i<8; ++i) (*rr++) -= (*cs++);
  /* #251: {@35, @8, @9, @43, @42, @41, @0, @45} = vertsplit(@32) */
  w35 = w32[0];
  w8 = w32[1];
  w9 = w32[2];
  w43 = w32[3];
  w42 = w32[4];
  w41 = w32[5];
  w0 = w32[6];
  w45 = w32[7];
  /* #252: (@39[4] = @35) */
  for (rr=w39+4, ss=(&w35); rr!=w39+5; rr+=1) *rr = *ss++;
  /* #253: (@39[5] = @8) */
  for (rr=w39+5, ss=(&w8); rr!=w39+6; rr+=1) *rr = *ss++;
  /* #254: (@39[6] = @9) */
  for (rr=w39+6, ss=(&w9); rr!=w39+7; rr+=1) *rr = *ss++;
  /* #255: @9 = cos(@5) */
  w9 = cos( w5 );
  /* #256: @28 = zeros(8x8) */
  casadi_clear(w28, 64);
  /* #257: @32 = @16' */
  casadi_copy(w16, 8, w32);
  /* #258: @28 = mac(@1,@32,@28) */
  for (i=0, rr=w28; i<8; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w1+j, tt=w32+i*1; k<1; ++k) *rr += ss[k*8]**tt++;
  /* #259: @18 = @28' */
  for (i=0, rr=w18, cs=w28; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #260: {@26, @21} = horzsplit(@18) */
  casadi_copy(w18, 32, w26);
  casadi_copy(w18+32, 32, w21);
  /* #261: @46 = @26' */
  for (i=0, rr=w46, cs=w26; i<4; ++i) for (j=0; j<8; ++j) rr[i+j*4] = *cs++;
  /* #262: {NULL, @19} = horzsplit(@46) */
  casadi_copy(w46+16, 16, w19);
  /* #263: @8 = 0 */
  w8 = 0.;
  /* #264: (@19[15] = @8) */
  for (rr=w19+15, ss=(&w8); rr!=w19+16; rr+=1) *rr = *ss++;
  /* #265: @8 = 0 */
  w8 = 0.;
  /* #266: (@19[11] = @8) */
  for (rr=w19+11, ss=(&w8); rr!=w19+12; rr+=1) *rr = *ss++;
  /* #267: @8 = 0 */
  w8 = 0.;
  /* #268: (@19[7] = @8) */
  for (rr=w19+7, ss=(&w8); rr!=w19+8; rr+=1) *rr = *ss++;
  /* #269: @8 = 0 */
  w8 = 0.;
  /* #270: (@19[3] = @8) */
  for (rr=w19+3, ss=(&w8); rr!=w19+4; rr+=1) *rr = *ss++;
  /* #271: @8 = 0 */
  w8 = 0.;
  /* #272: (@19[14] = @8) */
  for (rr=w19+14, ss=(&w8); rr!=w19+15; rr+=1) *rr = *ss++;
  /* #273: @8 = 0 */
  w8 = 0.;
  /* #274: (@19[10] = @8) */
  for (rr=w19+10, ss=(&w8); rr!=w19+11; rr+=1) *rr = *ss++;
  /* #275: @8 = 0 */
  w8 = 0.;
  /* #276: (@19[6] = @8) */
  for (rr=w19+6, ss=(&w8); rr!=w19+7; rr+=1) *rr = *ss++;
  /* #277: @8 = 0 */
  w8 = 0.;
  /* #278: (@19[2] = @8) */
  for (rr=w19+2, ss=(&w8); rr!=w19+3; rr+=1) *rr = *ss++;
  /* #279: @8 = 0 */
  w8 = 0.;
  /* #280: (@19[13] = @8) */
  for (rr=w19+13, ss=(&w8); rr!=w19+14; rr+=1) *rr = *ss++;
  /* #281: @8 = 0 */
  w8 = 0.;
  /* #282: (@19[9] = @8) */
  for (rr=w19+9, ss=(&w8); rr!=w19+10; rr+=1) *rr = *ss++;
  /* #283: @8 = 0 */
  w8 = 0.;
  /* #284: @24 = @19; (@24[5] = @8) */
  casadi_copy(w19, 16, w24);
  for (rr=w24+5, ss=(&w8); rr!=w24+6; rr+=1) *rr = *ss++;
  /* #285: @8 = @24[1] */
  for (rr=(&w8), ss=w24+1; ss!=w24+2; ss+=1) *rr++ = *ss;
  /* #286: @8 = (@9*@8) */
  w8  = (w9*w8);
  /* #287: @35 = sin(@5) */
  w35 = sin( w5 );
  /* #288: @47 = @19[5] */
  for (rr=(&w47), ss=w19+5; ss!=w19+6; ss+=1) *rr++ = *ss;
  /* #289: @47 = (@35*@47) */
  w47  = (w35*w47);
  /* #290: @8 = (@8-@47) */
  w8 -= w47;
  /* #291: @47 = cos(@5) */
  w47 = cos( w5 );
  /* #292: @48 = 0 */
  w48 = 0.;
  /* #293: (@24[1] = @48) */
  for (rr=w24+1, ss=(&w48); rr!=w24+2; rr+=1) *rr = *ss++;
  /* #294: @48 = 0 */
  w48 = 0.;
  /* #295: (@24[12] = @48) */
  for (rr=w24+12, ss=(&w48); rr!=w24+13; rr+=1) *rr = *ss++;
  /* #296: @48 = 0 */
  w48 = 0.;
  /* #297: (@24[8] = @48) */
  for (rr=w24+8, ss=(&w48); rr!=w24+9; rr+=1) *rr = *ss++;
  /* #298: @48 = @24[4] */
  for (rr=(&w48), ss=w24+4; ss!=w24+5; ss+=1) *rr++ = *ss;
  /* #299: @48 = (@47*@48) */
  w48  = (w47*w48);
  /* #300: @8 = (@8-@48) */
  w8 -= w48;
  /* #301: @5 = sin(@5) */
  w5 = sin( w5 );
  /* #302: @48 = 0 */
  w48 = 0.;
  /* #303: (@24[4] = @48) */
  for (rr=w24+4, ss=(&w48); rr!=w24+5; rr+=1) *rr = *ss++;
  /* #304: @48 = @24[0] */
  for (rr=(&w48), ss=w24+0; ss!=w24+1; ss+=1) *rr++ = *ss;
  /* #305: @48 = (@5*@48) */
  w48  = (w5*w48);
  /* #306: @8 = (@8-@48) */
  w8 -= w48;
  /* #307: @8 = (@8+@43) */
  w8 += w43;
  /* #308: (@39[7] = @8) */
  for (rr=w39+7, ss=(&w8); rr!=w39+8; rr+=1) *rr = *ss++;
  /* #309: (@39[8] = @42) */
  for (rr=w39+8, ss=(&w42); rr!=w39+9; rr+=1) *rr = *ss++;
  /* #310: (@39[9] = @41) */
  for (rr=w39+9, ss=(&w41); rr!=w39+10; rr+=1) *rr = *ss++;
  /* #311: (@39[10] = @0) */
  for (rr=w39+10, ss=(&w0); rr!=w39+11; rr+=1) *rr = *ss++;
  /* #312: @24 = zeros(4x4) */
  casadi_clear(w24, 16);
  /* #313: @19 = @23' */
  for (i=0, rr=w19, cs=w23; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #314: @46 = @21' */
  for (i=0, rr=w46, cs=w21; i<4; ++i) for (j=0; j<8; ++j) rr[i+j*4] = *cs++;
  /* #315: {NULL, @20} = horzsplit(@46) */
  casadi_copy(w46+16, 16, w20);
  /* #316: @20 = (-@20) */
  for (i=0, rr=w20, cs=w20; i<16; ++i) *rr++ = (- *cs++ );
  /* #317: @24 = mac(@19,@20,@24) */
  for (i=0, rr=w24; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w19+j, tt=w20+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #318: @0 = 0 */
  w0 = 0.;
  /* #319: (@24[15] = @0) */
  for (rr=w24+15, ss=(&w0); rr!=w24+16; rr+=1) *rr = *ss++;
  /* #320: @0 = 0 */
  w0 = 0.;
  /* #321: (@24[11] = @0) */
  for (rr=w24+11, ss=(&w0); rr!=w24+12; rr+=1) *rr = *ss++;
  /* #322: @0 = 0 */
  w0 = 0.;
  /* #323: (@24[7] = @0) */
  for (rr=w24+7, ss=(&w0); rr!=w24+8; rr+=1) *rr = *ss++;
  /* #324: @0 = 0 */
  w0 = 0.;
  /* #325: (@24[3] = @0) */
  for (rr=w24+3, ss=(&w0); rr!=w24+4; rr+=1) *rr = *ss++;
  /* #326: @0 = 0 */
  w0 = 0.;
  /* #327: (@24[14] = @0) */
  for (rr=w24+14, ss=(&w0); rr!=w24+15; rr+=1) *rr = *ss++;
  /* #328: @0 = 0 */
  w0 = 0.;
  /* #329: (@24[10] = @0) */
  for (rr=w24+10, ss=(&w0); rr!=w24+11; rr+=1) *rr = *ss++;
  /* #330: @0 = 0 */
  w0 = 0.;
  /* #331: (@24[6] = @0) */
  for (rr=w24+6, ss=(&w0); rr!=w24+7; rr+=1) *rr = *ss++;
  /* #332: @0 = 0 */
  w0 = 0.;
  /* #333: (@24[2] = @0) */
  for (rr=w24+2, ss=(&w0); rr!=w24+3; rr+=1) *rr = *ss++;
  /* #334: @0 = 0 */
  w0 = 0.;
  /* #335: (@24[13] = @0) */
  for (rr=w24+13, ss=(&w0); rr!=w24+14; rr+=1) *rr = *ss++;
  /* #336: @0 = 0 */
  w0 = 0.;
  /* #337: (@24[9] = @0) */
  for (rr=w24+9, ss=(&w0); rr!=w24+10; rr+=1) *rr = *ss++;
  /* #338: @0 = 0 */
  w0 = 0.;
  /* #339: (@24[5] = @0) */
  for (rr=w24+5, ss=(&w0); rr!=w24+6; rr+=1) *rr = *ss++;
  /* #340: @0 = @24[1] */
  for (rr=(&w0), ss=w24+1; ss!=w24+2; ss+=1) *rr++ = *ss;
  /* #341: @0 = (@6*@0) */
  w0  = (w6*w0);
  /* #342: @41 = 0 */
  w41 = 0.;
  /* #343: (@24[1] = @41) */
  for (rr=w24+1, ss=(&w41); rr!=w24+2; rr+=1) *rr = *ss++;
  /* #344: @41 = 0 */
  w41 = 0.;
  /* #345: (@24[12] = @41) */
  for (rr=w24+12, ss=(&w41); rr!=w24+13; rr+=1) *rr = *ss++;
  /* #346: @41 = 0 */
  w41 = 0.;
  /* #347: (@24[8] = @41) */
  for (rr=w24+8, ss=(&w41); rr!=w24+9; rr+=1) *rr = *ss++;
  /* #348: @41 = @24[4] */
  for (rr=(&w41), ss=w24+4; ss!=w24+5; ss+=1) *rr++ = *ss;
  /* #349: @41 = (@4*@41) */
  w41  = (w4*w41);
  /* #350: @0 = (@0+@41) */
  w0 += w41;
  /* #351: @0 = (@0+@45) */
  w0 += w45;
  /* #352: (@39[11] = @0) */
  for (rr=w39+11, ss=(&w0); rr!=w39+12; rr+=1) *rr = *ss++;
  /* #353: @38 = @38' */
  /* #354: @0 = ones(2x1,1nz) */
  w0 = 1.;
  /* #355: {NULL, @45} = vertsplit(@0) */
  w45 = w0;
  /* #356: @38 = (@38*@45) */
  for (i=0, rr=w38; i<4; ++i) (*rr++) *= w45;
  /* #357: {@0, @41, @42, @8} = vertsplit(@38) */
  w0 = w38[0];
  w41 = w38[1];
  w42 = w38[2];
  w8 = w38[3];
  /* #358: (@39[12] = @0) */
  for (rr=w39+12, ss=(&w0); rr!=w39+13; rr+=1) *rr = *ss++;
  /* #359: (@39[13] = @41) */
  for (rr=w39+13, ss=(&w41); rr!=w39+14; rr+=1) *rr = *ss++;
  /* #360: (@39[14] = @42) */
  for (rr=w39+14, ss=(&w42); rr!=w39+15; rr+=1) *rr = *ss++;
  /* #361: (@39[15] = @8) */
  for (rr=w39+15, ss=(&w8); rr!=w39+16; rr+=1) *rr = *ss++;
  /* #362: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #363: @13 = (@13/@12) */
  w13 /= w12;
  /* #364: @37 = zeros(1x8,2nz) */
  casadi_clear(w37, 2);
  /* #365: @30 = @30' */
  /* #366: @30 = (@45*@30) */
  for (i=0, rr=w30, cs=w30; i<4; ++i) (*rr++)  = (w45*(*cs++));
  /* #367: @37 = mac(@30,@22,@37) */
  casadi_mtimes(w30, casadi_s7, w22, casadi_s9, w37, casadi_s6, w, 0);
  /* #368: @1 = dense(@37) */
  casadi_densify(w37, casadi_s6, w1, 0);
  /* #369: @17 = @17' */
  /* #370: @17 = (@45*@17) */
  for (i=0, rr=w17, cs=w17; i<8; ++i) (*rr++)  = (w45*(*cs++));
  /* #371: @1 = (@1+@17) */
  for (i=0, rr=w1, cs=w17; i<8; ++i) (*rr++) += (*cs++);
  /* #372: @1 = @1' */
  /* #373: @8 = @1[1] */
  for (rr=(&w8), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #374: @13 = (@13*@8) */
  w13 *= w8;
  /* #375: @7 = (@7/@12) */
  w7 /= w12;
  /* #376: @42 = 0 */
  w42 = 0.;
  /* #377: (@1[1] = @42) */
  for (rr=w1+1, ss=(&w42); rr!=w1+2; rr+=1) *rr = *ss++;
  /* #378: @42 = @1[0] */
  for (rr=(&w42), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #379: @7 = (@7*@42) */
  w7 *= w42;
  /* #380: @13 = (@13+@7) */
  w13 += w7;
  /* #381: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #382: @13 = (@13-@45) */
  w13 -= w45;
  /* #383: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #384: @13 = (@13/@11) */
  w13 /= w11;
  /* #385: @2 = (@2*@13) */
  w2 *= w13;
  /* #386: @42 = (@42/@12) */
  w42 /= w12;
  /* #387: @10 = (@10*@42) */
  w10 *= w42;
  /* #388: @10 = (-@10) */
  w10 = (- w10 );
  /* #389: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #390: @2 = (@2+@10) */
  w2 += w10;
  /* #391: @1 = zeros(8x1) */
  casadi_clear(w1, 8);
  /* #392: @33 = (@33*@45) */
  for (i=0, rr=w33; i<2; ++i) (*rr++) *= w45;
  /* #393: @17 = dense(@33) */
  casadi_densify(w33, casadi_s10, w17, 0);
  /* #394: @1 = mac(@27,@17,@1) */
  for (i=0, rr=w1; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w27+j, tt=w17+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #395: {@45, @10, @42, @11, @7, @41, @0, @43} = vertsplit(@1) */
  w45 = w1[0];
  w10 = w1[1];
  w42 = w1[2];
  w11 = w1[3];
  w7 = w1[4];
  w41 = w1[5];
  w0 = w1[6];
  w43 = w1[7];
  /* #396: @2 = (@2+@45) */
  w2 += w45;
  /* #397: (@39[16] = @2) */
  for (rr=w39+16, ss=(&w2); rr!=w39+17; rr+=1) *rr = *ss++;
  /* #398: @8 = (@8/@12) */
  w8 /= w12;
  /* #399: @36 = (@36*@8) */
  w36 *= w8;
  /* #400: @36 = (-@36) */
  w36 = (- w36 );
  /* #401: @36 = (2.*@36) */
  w36 = (2.* w36 );
  /* #402: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #403: @3 = (@3*@13) */
  w3 *= w13;
  /* #404: @36 = (@36+@3) */
  w36 += w3;
  /* #405: @36 = (@36+@10) */
  w36 += w10;
  /* #406: (@39[17] = @36) */
  for (rr=w39+17, ss=(&w36); rr!=w39+18; rr+=1) *rr = *ss++;
  /* #407: (@39[18] = @42) */
  for (rr=w39+18, ss=(&w42); rr!=w39+19; rr+=1) *rr = *ss++;
  /* #408: @27 = zeros(8x8) */
  casadi_clear(w27, 64);
  /* #409: @16 = @16' */
  /* #410: @27 = mac(@17,@16,@27) */
  for (i=0, rr=w27; i<8; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w17+j, tt=w16+i*1; k<1; ++k) *rr += ss[k*8]**tt++;
  /* #411: @18 = @27' */
  for (i=0, rr=w18, cs=w27; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #412: {@22, @46} = horzsplit(@18) */
  casadi_copy(w18, 32, w22);
  casadi_copy(w18+32, 32, w46);
  /* #413: @21 = @22' */
  for (i=0, rr=w21, cs=w22; i<4; ++i) for (j=0; j<8; ++j) rr[i+j*4] = *cs++;
  /* #414: {NULL, @24} = horzsplit(@21) */
  casadi_copy(w21+16, 16, w24);
  /* #415: @42 = 0 */
  w42 = 0.;
  /* #416: (@24[15] = @42) */
  for (rr=w24+15, ss=(&w42); rr!=w24+16; rr+=1) *rr = *ss++;
  /* #417: @42 = 0 */
  w42 = 0.;
  /* #418: (@24[11] = @42) */
  for (rr=w24+11, ss=(&w42); rr!=w24+12; rr+=1) *rr = *ss++;
  /* #419: @42 = 0 */
  w42 = 0.;
  /* #420: (@24[7] = @42) */
  for (rr=w24+7, ss=(&w42); rr!=w24+8; rr+=1) *rr = *ss++;
  /* #421: @42 = 0 */
  w42 = 0.;
  /* #422: (@24[3] = @42) */
  for (rr=w24+3, ss=(&w42); rr!=w24+4; rr+=1) *rr = *ss++;
  /* #423: @42 = 0 */
  w42 = 0.;
  /* #424: (@24[14] = @42) */
  for (rr=w24+14, ss=(&w42); rr!=w24+15; rr+=1) *rr = *ss++;
  /* #425: @42 = 0 */
  w42 = 0.;
  /* #426: (@24[10] = @42) */
  for (rr=w24+10, ss=(&w42); rr!=w24+11; rr+=1) *rr = *ss++;
  /* #427: @42 = 0 */
  w42 = 0.;
  /* #428: (@24[6] = @42) */
  for (rr=w24+6, ss=(&w42); rr!=w24+7; rr+=1) *rr = *ss++;
  /* #429: @42 = 0 */
  w42 = 0.;
  /* #430: (@24[2] = @42) */
  for (rr=w24+2, ss=(&w42); rr!=w24+3; rr+=1) *rr = *ss++;
  /* #431: @42 = 0 */
  w42 = 0.;
  /* #432: (@24[13] = @42) */
  for (rr=w24+13, ss=(&w42); rr!=w24+14; rr+=1) *rr = *ss++;
  /* #433: @42 = 0 */
  w42 = 0.;
  /* #434: (@24[9] = @42) */
  for (rr=w24+9, ss=(&w42); rr!=w24+10; rr+=1) *rr = *ss++;
  /* #435: @42 = 0 */
  w42 = 0.;
  /* #436: @19 = @24; (@19[5] = @42) */
  casadi_copy(w24, 16, w19);
  for (rr=w19+5, ss=(&w42); rr!=w19+6; rr+=1) *rr = *ss++;
  /* #437: @42 = @19[1] */
  for (rr=(&w42), ss=w19+1; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #438: @9 = (@9*@42) */
  w9 *= w42;
  /* #439: @42 = @24[5] */
  for (rr=(&w42), ss=w24+5; ss!=w24+6; ss+=1) *rr++ = *ss;
  /* #440: @35 = (@35*@42) */
  w35 *= w42;
  /* #441: @9 = (@9-@35) */
  w9 -= w35;
  /* #442: @35 = 0 */
  w35 = 0.;
  /* #443: (@19[1] = @35) */
  for (rr=w19+1, ss=(&w35); rr!=w19+2; rr+=1) *rr = *ss++;
  /* #444: @35 = 0 */
  w35 = 0.;
  /* #445: (@19[12] = @35) */
  for (rr=w19+12, ss=(&w35); rr!=w19+13; rr+=1) *rr = *ss++;
  /* #446: @35 = 0 */
  w35 = 0.;
  /* #447: (@19[8] = @35) */
  for (rr=w19+8, ss=(&w35); rr!=w19+9; rr+=1) *rr = *ss++;
  /* #448: @35 = @19[4] */
  for (rr=(&w35), ss=w19+4; ss!=w19+5; ss+=1) *rr++ = *ss;
  /* #449: @47 = (@47*@35) */
  w47 *= w35;
  /* #450: @9 = (@9-@47) */
  w9 -= w47;
  /* #451: @47 = 0 */
  w47 = 0.;
  /* #452: (@19[4] = @47) */
  for (rr=w19+4, ss=(&w47); rr!=w19+5; rr+=1) *rr = *ss++;
  /* #453: @47 = @19[0] */
  for (rr=(&w47), ss=w19+0; ss!=w19+1; ss+=1) *rr++ = *ss;
  /* #454: @5 = (@5*@47) */
  w5 *= w47;
  /* #455: @9 = (@9-@5) */
  w9 -= w5;
  /* #456: @9 = (@9+@11) */
  w9 += w11;
  /* #457: (@39[19] = @9) */
  for (rr=w39+19, ss=(&w9); rr!=w39+20; rr+=1) *rr = *ss++;
  /* #458: (@39[20] = @7) */
  for (rr=w39+20, ss=(&w7); rr!=w39+21; rr+=1) *rr = *ss++;
  /* #459: (@39[21] = @41) */
  for (rr=w39+21, ss=(&w41); rr!=w39+22; rr+=1) *rr = *ss++;
  /* #460: (@39[22] = @0) */
  for (rr=w39+22, ss=(&w0); rr!=w39+23; rr+=1) *rr = *ss++;
  /* #461: @19 = zeros(4x4) */
  casadi_clear(w19, 16);
  /* #462: @24 = @23' */
  for (i=0, rr=w24, cs=w23; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #463: @21 = @46' */
  for (i=0, rr=w21, cs=w46; i<4; ++i) for (j=0; j<8; ++j) rr[i+j*4] = *cs++;
  /* #464: {NULL, @23} = horzsplit(@21) */
  casadi_copy(w21+16, 16, w23);
  /* #465: @23 = (-@23) */
  for (i=0, rr=w23, cs=w23; i<16; ++i) *rr++ = (- *cs++ );
  /* #466: @19 = mac(@24,@23,@19) */
  for (i=0, rr=w19; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w24+j, tt=w23+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #467: @0 = 0 */
  w0 = 0.;
  /* #468: (@19[15] = @0) */
  for (rr=w19+15, ss=(&w0); rr!=w19+16; rr+=1) *rr = *ss++;
  /* #469: @0 = 0 */
  w0 = 0.;
  /* #470: (@19[11] = @0) */
  for (rr=w19+11, ss=(&w0); rr!=w19+12; rr+=1) *rr = *ss++;
  /* #471: @0 = 0 */
  w0 = 0.;
  /* #472: (@19[7] = @0) */
  for (rr=w19+7, ss=(&w0); rr!=w19+8; rr+=1) *rr = *ss++;
  /* #473: @0 = 0 */
  w0 = 0.;
  /* #474: (@19[3] = @0) */
  for (rr=w19+3, ss=(&w0); rr!=w19+4; rr+=1) *rr = *ss++;
  /* #475: @0 = 0 */
  w0 = 0.;
  /* #476: (@19[14] = @0) */
  for (rr=w19+14, ss=(&w0); rr!=w19+15; rr+=1) *rr = *ss++;
  /* #477: @0 = 0 */
  w0 = 0.;
  /* #478: (@19[10] = @0) */
  for (rr=w19+10, ss=(&w0); rr!=w19+11; rr+=1) *rr = *ss++;
  /* #479: @0 = 0 */
  w0 = 0.;
  /* #480: (@19[6] = @0) */
  for (rr=w19+6, ss=(&w0); rr!=w19+7; rr+=1) *rr = *ss++;
  /* #481: @0 = 0 */
  w0 = 0.;
  /* #482: (@19[2] = @0) */
  for (rr=w19+2, ss=(&w0); rr!=w19+3; rr+=1) *rr = *ss++;
  /* #483: @0 = 0 */
  w0 = 0.;
  /* #484: (@19[13] = @0) */
  for (rr=w19+13, ss=(&w0); rr!=w19+14; rr+=1) *rr = *ss++;
  /* #485: @0 = 0 */
  w0 = 0.;
  /* #486: (@19[9] = @0) */
  for (rr=w19+9, ss=(&w0); rr!=w19+10; rr+=1) *rr = *ss++;
  /* #487: @0 = 0 */
  w0 = 0.;
  /* #488: (@19[5] = @0) */
  for (rr=w19+5, ss=(&w0); rr!=w19+6; rr+=1) *rr = *ss++;
  /* #489: @0 = @19[1] */
  for (rr=(&w0), ss=w19+1; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #490: @6 = (@6*@0) */
  w6 *= w0;
  /* #491: @0 = 0 */
  w0 = 0.;
  /* #492: (@19[1] = @0) */
  for (rr=w19+1, ss=(&w0); rr!=w19+2; rr+=1) *rr = *ss++;
  /* #493: @0 = 0 */
  w0 = 0.;
  /* #494: (@19[12] = @0) */
  for (rr=w19+12, ss=(&w0); rr!=w19+13; rr+=1) *rr = *ss++;
  /* #495: @0 = 0 */
  w0 = 0.;
  /* #496: (@19[8] = @0) */
  for (rr=w19+8, ss=(&w0); rr!=w19+9; rr+=1) *rr = *ss++;
  /* #497: @0 = @19[4] */
  for (rr=(&w0), ss=w19+4; ss!=w19+5; ss+=1) *rr++ = *ss;
  /* #498: @4 = (@4*@0) */
  w4 *= w0;
  /* #499: @6 = (@6+@4) */
  w6 += w4;
  /* #500: @6 = (@6+@43) */
  w6 += w43;
  /* #501: (@39[23] = @6) */
  for (rr=w39+23, ss=(&w6); rr!=w39+24; rr+=1) *rr = *ss++;
  /* #502: output[1][0] = @39 */
  casadi_copy(w39, 24, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_constr_h_fun_jac_uxt_zt_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_constr_h_fun_jac_uxt_zt_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_constr_h_fun_jac_uxt_zt_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s11;
    case 2: return casadi_s12;
    case 3: return casadi_s13;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s14;
    case 1: return casadi_s15;
    case 2: return casadi_s16;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 16;
  if (sz_res) *sz_res = 11;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 552;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
